export const PRISM_LANGUAGES: Array<{
  grammarName: string
  name: string
}> = [
  { grammarName: 'plain', name: 'Plain Text' },
  { grammarName: 'bash', name: 'Bash' },
  { grammarName: 'csharp', name: 'C#' },
  { grammarName: 'css', name: 'CSS' },
  { grammarName: 'cmake', name: 'CMake' },
  { grammarName: 'docker', name: 'Docker' },
  { grammarName: 'graphql', name: 'GraphQL' },
  { grammarName: 'xml', name: 'XML' },
  { grammarName: 'xml', name: 'HTML' },
  { grammarName: 'javascript', name: 'JavaScript' },
  { grammarName: 'json', name: 'JSON' },
  { grammarName: 'makefile', name: 'Makefile' },
  { grammarName: 'python', name: 'Python' },
  { grammarName: 'jsx', name: 'React JSX' },
  { grammarName: 'tsx', name: 'React TSX' },
  { grammarName: 'sql', name: 'SQL' },
  { grammarName: 'xml', name: 'SVG' },
  { grammarName: 'typescript', name: 'TypeScript' },
  { grammarName: 'yaml', name: 'YAML' },
  // { grammarName: 'antlr4', name: 'ANTLR4' },
  // { grammarName: 'c', name: 'C' },
  // { grammarName: 'coffeescript', name: 'CoffeeScript' },
  // { grammarName: 'django', name: 'Django' },
  // { grammarName: 'ejs', name: 'EJS' },
  // { grammarName: 'erlang', name: 'Erlang' },
  // { grammarName: 'git', name: 'Git' },
  // { grammarName: 'go', name: 'Go' },
  // { grammarName: 'groovy', name: 'Groovy' },
  // { grammarName: 'java', name: 'Java' },
  // { grammarName: 'kotlin', name: 'Kotlin' },
  // { grammarName: 'latex', name: 'LaTeX' },
  // { grammarName: 'less', name: 'Less' },
  // { grammarName: 'lua', name: 'Lua' },
  // { grammarName: 'markdown', name: 'Markdown' },
  // { grammarName: 'matlab', name: 'MATLAB' },
  // { grammarName: 'markup', name: 'Markup' },
  // { grammarName: 'objectivec', name: 'Objective-C' },
  // { grammarName: 'perl', name: 'Perl' },
  // { grammarName: 'php', name: 'PHP' },
  // { grammarName: 'powershell', name: 'PowerShell' },
  // { grammarName: 'properties', name: '.properties' },
  // { grammarName: 'protobuf', name: 'Protocol Buffers' },
  // { grammarName: 'r', name: 'R' },
  // { grammarName: 'ruby', name: 'Ruby' },
  // { grammarName: 'sass', name: 'Sass (Sass)' },
  // { grammarName: 'scss', name: 'Sass (Scss)' },
  // { grammarName: 'scala', name: 'Scala' },
  // { grammarName: 'scheme', name: 'Scheme' },
  // { grammarName: 'shell', name: 'Shell' },
  // { grammarName: 'swift', name: 'Swift' },
  // { grammarName: 'wasm', name: 'WebAssembly' },
  // { grammarName: 'xml', name: 'XML' },
]
